# SWC Bash 1-3 Summary

## 1 Bash 
Look at this bash shell. Isn't it neat? Wouldn't you think this file collection is complete? 

- Allows you to get down and dirty with what you might usually do with a GUI.
- Works in a "read-evaluate-print loop" REPL format -- meaning : "It is called so because when you type a command and press Return the shell reads your command, evaluates (or “executes”) it, prints the output of your command, loops back and waits for you to enter another command."

- Demo of bopping around in a terminal vs file finder. 
- Anatomy of a command with `ls -F /`
- `ls` is the command, `-F` is the flag (denoted with 1/2 dashes), and `/` is the argument -- where you are telling `ls` to do it's thing. 

- What does a broken command look like : ex `ls-F`

- Example problem we'll work through :
With 1520 samples that all need thirty seconds each to run, how can this be done thoughtfully with bash scripting? 

#### Key Points
- A shell is a program whose primary purpose is to read commands and run other programs.

- The shell’s main advantages are its high action-to-keystroke ratio, its support for automating repetitive tasks, and its capacity to access networked machines.

- The shell’s main disadvantages are its primarily textual nature and how cryptic its commands and operation can be.

# 2 Bash
Let's do move around in a terminal like pros. 


- Some of this may differ for windows machines. Sticky it up.
- `pwd`
- `home directory` -- usually something like `/Users/nelle`
- `/` denotes directories 
- `ls` (listing)
- lots'o'flags (like `-F`, `-a`, `-l`, `-h` `-R` `-t` etc.
- check `man ls` for all the info`
- `cd` changes directory
- sans argument it takes you to your home directory
- try an error
- `..` means one directory up, `.` means currently directory, `-` means previous directory, and `~` means home directory 
- (you can see `..` and `.` only with `ls -a`)
- tab complete is bae for files names 
- relative and absolut paths

#### Key Points 
- The file system is responsible for managing information on the disk.
- Information is stored in files, which are stored in directories (folders).
- Directories can also store other directories, which forms a directory tree.
- `cd path` changes the current working directory.
- `ls path` prints a listing of a specific file or directory; ls on its own lists the current working directory.
- `pwd` prints the user’s current working directory.
- `/` on its own is the root directory of the whole file system.
- A relative path specifies a location starting from the current location.
- An absolute path specifies a location from the root of the file system.
- Directory names in a path are separated with / on Unix, but \ on Windows.
- .. means ‘the directory above the current one’; . on its own means ‘the current directory’.
- Most files’ names are something.extension. The extension isn’t required, and doesn’t guarantee anything, but is normally used to indicate the type of data in the file.

In [2]:
1

1

In [3]:
2

2

In [4]:
1+2

3

In [5]:
1.


1.0

In [6]:
2.0

2.0

In [7]:
type(2.0)


float

In [8]:
1.*2.

2.0

In [9]:
1*2.

2.0

In [10]:
1/2

0.5

In [11]:
2-3

-1

In [12]:
2**3

8

In [13]:
import math

In [14]:
help(math)

Help on module math:

NAME
    math

MODULE REFERENCE
    https://docs.python.org/3.6/library/math
    
    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
    This module is always available.  It provides access to the
    mathematical functions defined by the C standard.

FUNCTIONS
    acos(...)
        acos(x)
        
        Return the arc cosine (measured in radians) of x.
    
    acosh(...)
        acosh(x)
        
        Return the inverse hyperbolic cosine of x.
    
    asin(...)
        asin(x)
        
        Return the arc sine (measured in radians) of x.
    
    asinh(...)
        asinh(x)
        
        Return the inverse hyperbolic sine of x.
    
    atan(...)
        atan(x)
        
 

In [15]:
dir(math)

['__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'pi',
 'pow',
 'radians',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc']

In [16]:
dir(1.0)

['__abs__',
 '__add__',
 '__bool__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getformat__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__le__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmod__',
 '__rmul__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__setattr__',
 '__setformat__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 'as_integer_ratio',
 'conjugate',
 'fromhex',
 'hex',
 'imag',
 'is_integer',
 'real']

In [17]:
1.real

SyntaxError: invalid syntax (<ipython-input-17-4958a24f298b>, line 1)

In [19]:
(1.0).real

1.0

In [20]:
math.

SyntaxError: invalid syntax (<ipython-input-20-186ff497df9b>, line 1)

In [21]:
math.log2(8)

3.0

In [22]:
'star'

'star'

In [23]:
'shooting' + 'start'

'shootingstart'

In [24]:
'star'*3

'starstarstar'

In [25]:
'star'[0]

's'

In [26]:
'star'[0:2]

'st'

In [27]:
'star'[:2]

'st'

In [29]:
'star'[2:]

'ar'

In [31]:
y = 'star'
y[0]

's'

In [32]:
y[-1]

'r'

In [33]:
y[-2]

'a'

In [34]:
y[:-2]

'st'

In [35]:
y = 3
z = 10
y+z 

13

In [37]:
i, j = 3, 10
i+j

13

In [38]:
my_list = [1, 2, 3]

In [39]:
mylist2 = ['a', 1, 'b', 'train']

In [41]:
my_list + mylist2

[1, 2, 3, 'a', 1, 'b', 'train']

In [42]:
my_list*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [44]:
my_list[2]

3

In [45]:
import numpy as np

In [47]:
my_array = np.array(my_list)
my_array

array([1, 2, 3])

In [48]:
type(my_array)

numpy.ndarray

In [49]:
type(my_list)

list

In [50]:
np.array(my_array)

array([1, 2, 3])

In [51]:
list(my_array)

[1, 2, 3]

In [55]:
np_array = np.array([1, 30, 39302, 2.0, 4])

In [62]:
np_array.mean()

1.5

In [63]:
np.mean(np_array)

1.5

In [58]:
np_array = np.array([[0, 1, 3], 
                     [3, 2, 0]])

In [61]:
np_array.mean(axis=1)

array([ 1.33333333,  1.66666667])

In [64]:
np_array.size

6

In [66]:
np_array.shape

(2, 3)

In [67]:
my_favorite_stars = ['sirius', 'deneb', 'altair']
for star in my_favorite_stars:
    print('one of my favorite stars is', star)

one of my favorite stars is sirius
one of my favorite stars is deneb
one of my favorite stars is altair


In [70]:
constellation = 'cygnus'
if constellation == 'cygnus':
    print('cygnus is my favorite constellation')
else:
    print('{} is not my favorite constellation'.format(constellation))

cygnus is my favorite constellation


In [71]:
constellation = 'lyra'
if constellation == 'cygnus':
    print('cygnus is my favorite constellation')
else:
    print('{} is not my favorite constellation'.format(constellation))

lyra is not my favorite constellation


In [73]:
for constellation in ['cygnus', 'lyra']:
    if constellation == 'cygnus':
        print('cygnus is my favorite constellation')
    else:
        print('{} is not my favorite constellation'.format(constellation))
    

cygnus is my favorite constellation
lyra is not my favorite constellation


In [74]:
for star in my_favorite_stars:
    if len(star) == 6:
        print(star)
    else:
        print('length of name {} is too short'.format(star))

sirius
length of name deneb is too short
altair


In [76]:
my_list = [1, 2, 5, 7, 9, 4, 5, 4]

# Find the total 
total = 0
for num in my_list:
    total = total + num

# Calculate the name
mean = total/len(my_list)

# Find the median
sorted_list = sorted(my_list)
if len(my_list)%2==1:
    median_index = int(len(my_list)/2)
    median = sorted_list[median_index]
else:
    median_index = int(len(my_list)/2)
    median = (sorted_list[median_index]+sorted_list[median_index-1])/2.
print(mean, median)
print(np.mean(my_list), np.median(my_list))


4.625 4.5
4.625 4.5


In [78]:
def calc_total(my_list):
    """
    Calculates the total!
    
    Parameters
    ----------
    my_list : list
        My list.
    
    Returns
    -------
    total : int/float
        The total sum of my list.
    """
    total = 0
    for num in my_list:
        total = total + num
    return total

def calc_mean(my_list):
    total = calc_total(my_list)
    list_length = len(my_list)
    mean = total/list_length
    return mean

def calc_median(my_list):
    sorted_list = sorted(my_list)
    if len(my_list)%2 == 1:
        median_index = int(len(my_list)/2)
        median = sorted_list[median_index]
    else:
        median_index = int(len(my_list)/2)
        median = (sorted_list[median_index]+sorted_list[median_index-1])/2.
    return median

my_list = [1, 2, 5, 7, 9, 4, 5, 4]
mean = calc_mean(my_list)
median = calc_median(my_list)
print(mean, median)

4.625 4.5


In [79]:
help(calc_total)

Help on function calc_total in module __main__:

calc_total(my_list)
    Calculates the total!
    
    Parameters
    ----------
    my_list : list
        My list.
    
    Returns
    -------
    total : int/float
        The total sum of my list.



In [ ]:
from astropy.io import ascii as asc
import astropy.units as u
